source_url: https://clawhub.ai/JimLiuxinghai/find-skills
download_url: https://wry-manatee-359.convex.site/api/v1/download?slug=find-skills
owner_id: kn77ajmmqw3cgnc3ay1x3e0ccd805hsw
slug: find-skills
version: 0.1.0
published_at_unix_ms: 1769698710765
